ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS assignee VARCHAR(80),
  ADD COLUMN IF NOT EXISTS tags VARCHAR(255),
  ADD COLUMN IF NOT EXISTS estimate_hours INTEGER,
  ADD COLUMN IF NOT EXISTS archived BOOLEAN NOT NULL DEFAULT FALSE;
