ALTER TABLE tasks ADD COLUMN IF NOT EXISTS assignee VARCHAR(80);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS tags VARCHAR(255);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS estimate_hours INTEGER;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS archived BOOLEAN NOT NULL DEFAULT FALSE;