spring:
  application:
    name: taskmanager
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: ${PORT:8080}
  address: 0.0.0.0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: "${APP_JWT_SECRET:change-this-secret-in-prod-please-very-long}"
    access-expiration-minutes: 30
    refresh-expiration-minutes: 43200

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5,0.95,0.99
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    root: INFO

loki:
  url: ${LOKI_URL:}
  app: taskmanager
